python/lsst/sconsUtils/builders.py
python/lsst/sconsUtils/dependencies.py
python/lsst/sconsUtils/eupsForScons.py

On creation, the current implementation of Eups class loads the entire product stack database, which can take a long time on systems where the stack has thousands of products.

Avoid repeated creation of Eups object

---

python/lsst/sconsUtils/builders.py
python/lsst/sconsUtils/state.py

This makes it possible for install_name_tool to reliably modify RPATH names
after builds (to make the code relocatable).
Ref.: https://annoyingtechnicaldetails.wordpress.com/2007/04/18/install_name_tool-changing-install-names-cant-be-redone-for-for-architecture-ppc-because-larger-updated-load-commands-do-not-fit-the-program-must-be-relinked/

Add -headerpad_max_install_names to linker flags on OS X

---

python/lsst/sconsUtils/state.py

$CC may be something like "gcc-4.8", which needs to be recognised as gcc.
Note also that "gcc-4.8 --version" produces something like:
gcc-4.8 (Homebrew gcc48 4.8.4) 4.8.4
so we have to deal with that additional "-4.8".

recognise gcc with appended version

---

python/lsst/sconsUtils/scripts.py

We list the failed tests after dumping the contents of the
.failed files so that eups distrib will be able to report
the failed tests properly.
Switch to .format() for string formatting so as to not repeat
"testsDir" four distinct times.

List failed tests and the content of the .failed files

---

python/lsst/sconsUtils/tests.py
python/lsst/sconsUtils/utils.py

This allows the logic to be reused by other components that
are trying to launch commands.

Move code that handles LSST_LIBRARY_PATH from tests to utils

---

python/lsst/sconsUtils/builders.py

For the new documentation, Breathe will bridge Doxygen's C++ API
reference docs to Sphinx. Breathe uses XML as its input.
HTML output is currently retained for backwards compatibility with the
existing documentation infrastructure.
For DM-4900.

DM-4900 Add XML as a doxygen output

---

python/lsst/sconsUtils/state.py

Adds the ability to set the `MACOSX_DEPLOYMENT_TARGET`, which affects
ABI compatibility on OSX.

add macosx_deployment_target flag

---

python/lsst/sconsUtils/state.py

Provides a workaround on OSX for the bug linking indirect libraries on OS X. Since I was messing with that code there is a second commit that cleans up the -install_name option and also switches that to use @rpath (which seems to be the recommended thing to do on OS X).

tickets/DM-5753: XCode 7.3 is broken 

---

python/lsst/sconsUtils/scripts.py
python/lsst/sconsUtils/utils.py

Do not ask the Python running SCons for its sys.executable.
This is needed when we do not know if the SCons python is the
same python we wish to use to run the applications built by
SCons.

Ask python on path where it is located

---

python/lsst/sconsUtils/scripts.py

This allows users to specfiy additional source files
for a given module.

Add extraSrc option to pybind11

---

python/lsst/sconsUtils/builders.py

Sorting wasn't working before, leading to spurious rebuilds due to
dependency order changes when the list of top-level build targets
changes.
I'm not sure all of these changes are necessary to fix it - using
Flatten() may have been all we needed - but sorting by str certainly
makes it easier to debug (without that it's not clear how scons sorts
File objects) and always returning SharedObjects avoids having any
intermediate steps where the sort order could get messed up.

Fix lack of sorting in SourcesForSharedLibrary.

---

python/lsst/sconsUtils/scripts.py

New code should specify False for this flag,
so that the python extension library name matches the source file name.

DM-9462: Allow disabling adding underscores to pybind11 library names

---

python/lsst/sconsUtils/state.py

Avoid confusion by using clang if this is really clang rather than using gcc.
Without this if you type `scons` you get `gcc` but it's really `clang`.

DM-12014: Use clang if no compiler was given and gcc is clang

---

python/lsst/sconsUtils/state.py

This env var needs to be passed through for unit tests that cover code sections that call out to eups.

preserve EUPS_USERDATA env var

---

python/lsst/sconsUtils/tests.py

This is mostly because of a problem with SEGV on import in C++ code which will never work. Without this xdist keeps creating workers until the process runs out of resources.

Stop xdist restarting workers if they won't start

---

python/lsst/sconsUtils/builders.py

This PR fixes a bug that was found in `sconsUtils` while working on DM-11016. Previously, `base.inc` was included in Doxygen config files after lines that appended other Stack packages to `TAGFILES`. Since a version update in 2014, `base.inc` contained the default (empty) `TAGFILES` line, which would supersede the appends written by `sconsUtils`.
This PR reorders the code so that include files always appear first on configs, guaranteeing that lines added by `sconsUtils` will take precedence regardless of the content of `base.inc` or any other `.inc` file.

DM-11016: Add standard library tag file to Doxygen

---

python/lsst/sconsUtils/tests.py

When starting a Python interpreter, it will add its own site-packages
directory to sys.path if it's not already there.
Normally, this works fine. However, when the same interpreter can be accessed
through two different paths, it can cause both of those paths to be added to
sys.path.
For example, in our standard, newinstall.sh provided, environment, we might
refer to the Python interpreter either as:
/ssd/lsstsw/stack3_20171021/python/miniconda3-4.3.21/bin/python
or as:
/ssd/lsstsw/stack3_20171021/python/current/bin/python
If we include the former's site packages directory corresponding to the former
on our $PYTHONPATH and then run it, everything is fine. Howver, if we instead
invoke the latter, it will insert a new site-packages directory,
corresponding to that provided by Miniconda, to …

DM-12454: Be explicit about which python pytest-xdist uses.

---

python/lsst/sconsUtils/state.py

DM-10342: Switch to C++14

---

python/lsst/sconsUtils/tests.py

xdist does not handle a space in the path when parsing the command line option, so for now we fall back to the original scheme of not specifying it at all if the path is not compatible.

Do not force worker python executable if space is in path

---

python/lsst/sconsUtils/scripts.py
python/lsst/sconsUtils/state.py

The compiler check in lsst.sconsUtils.state._configureCommon
fires whenever you import lsst.sconsUtils, even if you don't
have any C++ code and all you want out of lsst.sconsUtils is
some utility completely unrelated to C++. Besides just wasting
time, this makes it difficult to run ci_hsc on a cluster nodes
that don't have the latest gcc installed.
Instead, have the compiler check only fire when we need it, as
defined by instantiating BasicSConstruct. The compiler check
can also be disabled when using BasicSConstruct by instantiating
it with disableCc=True.

DM-13910: make compiler check fire only when needed

---

python/lsst/sconsUtils/builders.py

DM-15790: Compile pybind11 with hidden symbol visibility on linux

---

.gitignore
python/lsst/sconsUtils/tests.py
ups/sconsUtils.table

This fix prevents a full duplicate pytest execution during the install phase.
Pytest's session is aware of what tests ran, and by default, it will try to rerun all tests. This PR well set the `--last-failed-no-failures` behavior based on the scons goal. If it's `install`, it will tell pytest to skip running tests, though pytest will still run to determine if tests may have changed in that time frame.
After the first pytest runs successfully, we store the test outputs.
If no tests run (pytest will exit with code 5), we re-stage the original results, as pytest will still write output if no tests run.

DM-11693: Prevent double running of tests during build install

---

python/lsst/sconsUtils/tests.py

On unsupported platforms, the shell that the SCons commands may not be bash compatible.

DM-15829: Use bourne shell semantics for SCons commands

---

python/lsst/sconsUtils/tests.py

If we are supplying the `--last-failed-no-failures` flag (`lfnfOpt`) with the value of `all`, then make sure to delete the previous target files before executing the SCons command. 
If we are invoking SCons for an install, we set the `lfnfOpt = "none"`, otherwise it's all.

DM-15851: Clean target files if we are not performing an install

---

python/lsst/sconsUtils/tests.py

The escaped newline backslash was causing a problem in ubuntu 18.04.

DM-15851 Hotfix: Don't try to escape newline if prepending command

---

python/lsst/sconsUtils/utils.py

Standardize on the modern way for running external commands.

DM-16220: Use subprocess.run for all external commands

---

python/lsst/sconsUtils/state.py

by propagating the TERM envvar through scons, as proposed:
https://stackoverflow.com/a/9954572
This should not affect the compilation of anything, but only
the format of the outputs.

allow color outputs from compilers

---

python/lsst/sconsUtils/state.py

This environment variable was very rarely used, was broken (it is inserted in the wrong place), and has other workarounds (pseudo-packages).

Remove LSST_CFG_PATH.

---

python/lsst/sconsUtils/tests.py
tests/test_simple.py

Astropy needs to be able to find its cache files

DM-21286: Set XDG_CACHE_HOME for use by Astropy

---

python/lsst/sconsUtils/tests.py

Without this there are sometimes race conditions in test file collection.

DM-22182: Hide the doxygen build directories from pytest

---

configs/apr.cfg
configs/apr_util.cfg
configs/boost.cfg
configs/boost_filesystem.cfg
configs/boost_math.cfg
configs/boost_program_options.cfg
configs/boost_regex.cfg
configs/boost_serialization.cfg
configs/boost_system.cfg
configs/boost_test.cfg
configs/boost_thread.cfg
configs/cfitsio.cfg
configs/eigen.cfg
configs/fftw.cfg
configs/galsim.cfg
configs/gsl.cfg
configs/log4cxx.cfg
configs/minuit2.cfg
configs/ndarray.cfg
configs/numpy.cfg
configs/pybind11.cfg
configs/python.cfg
configs/starlink_ast.cfg
configs/xpa.cfg
python/lsst/sconsUtils/dependencies.py
python/lsst/sconsUtils/state.py
python/lsst/sconsUtils/utils.py
ups/sconsUtils.table

This PR adds cfg files for third parties in the config directory.
It also contains logic to support those config files.
In addition, it has additional support for `CONDA_BUILD_SYSROOT` for the conda compilers, especially on macOS, and it will prefer using conda compilers if it encounters `CONDA_BUILD_SYSROOT`

DM-23835: Support conda compilers and conda third parties

---

python/lsst/sconsUtils/tests.py

matplotlib 2 no longer needs this work around and setting
the variable did cause builds to slow down.
Note that other packages do use the presence of TRAVIS
env var to adjust how they run tests.

DM-4752: No longer set TRAVIS env var

---

configs/boost_timer.cfg

This PR adds an entry for the compiled version of the Boost Timer library. Pipelines code previously used the header-only version of timer, but this is now deprecated.

DM-27696: Fix Boost deprecation warning in afw

---

python/lsst/sconsUtils/scripts.py
python/lsst/sconsUtils/tests.py

This reverses #85 and tries a different solution. The race condition always seems to involve .tmp files so target those explicitly.

DM-29139: Update ignore glob in pytest test collection to include *.tmp

---

doc/lsst.sconsUtils/index.rst
python/lsst/sconsUtils/state.py
python/lsst/sconsUtils/utils.py

This PR detects conda build via the standard env var instead of depending on the sysroot variable.

REF detect conda compilers by looking for conda build too

---

python/lsst/sconsUtils/dependencies.py

The `info` message will only be displayed if the `--verbose` flag is used in the sconsUtils custom logger.  This gives the desired result that the message is typically suppressed unless the user asks for verbose output.

DM-24719: Change normal EUPS log to info from warn.

---

python/lsst/sconsUtils/tests.py

Not really due to the default branch change, but fixing the same terminology.

DM-32648: Change pytest-xdist term to 'controller'.

---

python/lsst/sconsUtils/tests.py

Some tests can take much longer than other tests and it can
be useful to report the longest ones.

DM-33125: Enable test duration reporting

---

setup.cfg

Otherwise it may walk up the directory tree looking for a pytest.ini.
Fixes #100 
Alternative to #101

DM-33727: Ensure that pytest uses a local configuration

---

python/lsst/sconsUtils/scripts.py

It's no longer created by pytest.

DM-14589: Remove .cache from clean target

---

.github/workflows/build.yaml
configs/python.cfg
python/lsst/sconsUtils/state.py

11.0 is the oldest OS version that supports arm64.

DM-34666: Set macOS deployment target to 11.0 on ARM systems

---

ups/sconsUtils.cfg

This PR stops any package that imports `sconsUtils` from expecting a Doxygen tag file.

DM-12659: Clean up Doxygen tagfile imports

---

.github/workflows/build.yaml
python/lsst/sconsUtils/tests.py

This allows scons tests to run on USDF and other locations that need proxies to connect to the internet for tests that it (including anything with astropy.time).

DM-36237: Pass through http proxy variables to tests.

---

python/lsst/sconsUtils/tests.py

Need this until ruff adds support for `.gitignore` outside of a git repo. (astral-sh/ruff#5930).

Also skip bin directory with ruff

---

configs/boost_timer.cfg

This PR allows the compiled library from [Boost Timer](https://www.boost.org/doc/libs/1_84_0/libs/timer/doc/index.html) 2 to be used in production code, not just test code (version 1 of the library was header-only). It must be merged before lsst/ip_diffim#298.

DM-42999: Enable Boost Timer version 2 in production code

---

.github/workflows/build.yaml
.gitignore
.pre-commit-config.yaml
python/lsst/sconsUtils/builders.py
python/lsst/sconsUtils/scripts.py
python/lsst/sconsUtils/state.py

This writes an egg-info directory into the python directory, enabling entry points and importlib.metadata to function using standard Python interfaces.

DM-42226: Write python package metadata

---

python/lsst/sconsUtils/builders.py
python/lsst/sconsUtils/scripts.py

The RECORD file allows packages_distributions to correctly find the sconsUtils packages.

DM-48284: Write RECORD and INSTALLER files to dist-info directory

---

.pre-commit-config.yaml
python/lsst/sconsUtils/builders.py
python/lsst/sconsUtils/tests.py

Remember that linux has a very small (127) character shebang limit and /usr/bin/env should be used all the time except for cases where SIP is involved on macOS.

DM-48776: Choose shebang rewriting for pyproject scripts to match shebang target

---

python/lsst/sconsUtils/state.py
python/lsst/sconsUtils/tests.py

Previously these were only forwarded when running tests.

DM-48797: Always forward environment variables needed for scripts
